### ISSUE TITLE
Missing BoostQueryTreeBuilder ?

### ISSUE THREAD

**Issue by mjustice3** [flaxsearch/luwak#108]
I'm in the process of upgrading from Solr/Lucene 5.3.2 to 6.3.0 and found that the presearcher basically stopped filtering. Adding a BoostQueryTreeBuilder  fixes the problem.

**Comment by romseygeek** [comment]
Oops, good catch.  Do you have a PR?

**Comment by mjustice3** [comment]
PR #109

**Comment by dcollins53** [comment]
Is there any documentation on "supporting new query types"?  I have an issue with https://github.com/flaxsearch/luwak/blob/master/luwak/src/main/java/uk/co/flax/luwak/util/SpanRewriter.java as well, but I guess we need some way of ensuring that 

a) we support all the "inbuilt" lucene query types
b) we can extend that ideally without having to update any Luwak code, by extension?

**Comment by romseygeek** [comment]
Re making the presearcher aware of new query types, see https://github.com/flaxsearch/luwak#adding-new-query-types

Re supporting all core query types, that would be a good thing to aim at, definitely.  I've created a branch with a test that checks all Query types in the org.apache.lucene namespace (or at least, those that are in the luwak classpath) - see #110.  Let's continue the discussion there.

**Comment by romseygeek** [comment]
I've merged in #109 - thanks Marvin!
