### ISSUE TITLE
Luwak doesn't respect non-default position and increment gaps for multi-valued fields

### ISSUE THREAD

**Issue by mjustice3** [flaxsearch/luwak#116]

**Comment by mjustice3** [comment]
PR #117

**Comment by mjustice3** [comment]
We have proximity queries that are matching against multi-valued fields where they shouldn't be. Seems like this used to work, before the DocumentBatch refactoring maybe?

**Comment by romseygeek** [comment]
Fixed by e1c6e577779770fb988e7739bae70c8c85b9c176
