### ISSUE TITLE
omitnorms

### ISSUE THREAD

**Issue by matteogrolla** [flaxsearch/luwak#135]
Hi I'm working with Luwak 1.3.0 and I build the lucene document that I pass to luwak specifying that a particular field has omitNorms=true
When I look at the score explanation with explainingmatcher I see that fieldNorm for that field is not 1, as expected, but 0.375.
So lucene seems to be ignoring omitnorms.
Can you hint me on why this happens? And how to fix it?

**Comment by romseygeek** [comment]
Hi, can you write a test case to show how you're using this?

**Comment by matteogrolla** [comment]
Hi Alan,
       what I see is that
DocumentBatch$SingletonDocumentBatch
      calls memoryindex.freeze()
      which for every field callas
           MemoryIndex$Info.getNormDocValues()
                 that (lazily) computes norms ignoring omitnorms

seems an easy fix now that I understood how it works
What I'm doing is trying to make luwak compute the same scores as solr
so I created a custom similarity that reads idf values from the solr index.
Did someone else do it?

2017-02-03 20:18 GMT+01:00 Alan Woodward <notifications@github.com>:

**Comment by romseygeek** [comment]
Ah, OK, so this sounds like it's a bug in MemoryIndex then.  I'll open a lucene JIRA for it.

I'm afraid I don't know if anybody else has tried to build custom similarities in that way.  Sounds like an interesting idea though

**Comment by matteogrolla** [comment]
Thanks for opening a jira
I'll keep you posted then!

2017-02-06 17:22 GMT+01:00 Alan Woodward <notifications@github.com>:

**Comment by romseygeek** [comment]
This will be fixed by https://issues.apache.org/jira/browse/LUCENE-7679, in lucene 6.5

**Comment by romseygeek** [comment]
Fixed by 1.5 release
