### ISSUE TITLE
Update to lucene 6.x

### ISSUE THREAD

**Issue by magro** [flaxsearch/luwak#138]
We want to use luwak in a code base with lucene 6.4, therefore luwak needs to be updated. 

Is anybody already working on this?

**Comment by romseygeek** [comment]
Hi, the master branch is currently sitting on 6.3.  6.5 will be released in the next few weeks, and at that point I'll upgrade to that and do a 1.5 release (we have a couple of issues that will be fixed by the lucene 6.5 release).

**Comment by magro** [comment]
Awesome! Do you mind publishing an intermediate release (maybe as RC)? Otherwise we'd have to push s.th. to bintray so that we can use it.

**Comment by romseygeek** [comment]
I don't think I'm going to have time to publish a release in the next couple of weeks, but I can push something out in early April if lucene 6.5 hasn't landed by then.

**Comment by magro** [comment]
Ok, thanks! For now I've pushed a version to [bintray](https://bintray.com/magro/maven/luwak), we'll play with this one until you've published a release.
