### ISSUE TITLE
integrating luwak with solr

### ISSUE THREAD

**Issue by nik9839** [flaxsearch/luwak#140]
Hello,
I am trying to integrate luwak with solr, but i am unable to do it.
Can someone please tell me what changes i need to do in solr schema file.

**Comment by romseygeek** [comment]
Hi, what do you mean by 'integrate with solr'?  If you mean, use the same document structure for both Solr and luwak documents, then you'll need to set up your analysis chains to be the same for both.

**Comment by nik9839** [comment]
Hii,
I want to do this-
How to use Luwak to run preset queries against incoming documents .

The content in this is thing i want to implement.
http://opensourceconnections.com/blog/2016/02/05/luwak/

**Comment by flaxsearch** [comment]
Hi, you can certainly use Luwak as a base for building this kind of system. You might be interested in an early version of a web service that uses Luwak - see 'luwak server' in https://github.com/flaxsearch/luwak/tree/luwak-server - this is pretty easy to get up and running.

**Comment by nik9839** [comment]
Apart from this, how can we add queries with proximity.

For example, if my query is- "student of  university" and proximity declared is 1,
and the input document has a sub-strings like ->"student of xyz university" or "student abc(any word) of xyz university".
Then it should give hit for both these document.

**Comment by nik9839** [comment]
Done.
I can use QueryMatch for this.
