### ISSUE TITLE
testPhraseQuery in TestSpanRewriter fails?

### ISSUE THREAD

**Issue by dcollins53** [flaxsearch/luwak#144]
After the latest commit 0ae0107044fa9ca44764b7092feff3753b59d42c, the test case for testPhraseQuery in TestSpanRewriter fails.  It is expecting a SpanNearQuery, but it gets a SpanOffsetReportingQuery as per that latest update.

Is there any scenario whereby we can still return a SpanNearQuery?

**Comment by romseygeek** [comment]
Hm, I ought to be getting notifications from travis when I break the build.

We always need to return SpanOffsetReportingQuery from the rewriter, so the test needs to be changed to reflect that.  Although maybe we can wrap the top-level SpanQueries elsewhere?

**Comment by romseygeek** [comment]
Fixed by 462d67f33c0591bdd95cb4e8a80c964008d25dcd
