### ISSUE TITLE
IntPoint Fields

### ISSUE THREAD

**Issue by shawnfeldman** [flaxsearch/luwak#147]
Do IntPoint fields work? The code below doesn't seem to pass in the latest from master

``` 
public void matchIntPointfields() throws IOException,UpdateException {
        monitor = new Monitor(new LuceneQueryParser("age"), new MatchAllPresearcher());
        InputDocument doc = InputDocument.builder("doc1")
                .addField(new IntPoint("age",1))
                .build();

        MonitorQuery mq  = new MonitorQuery("query1","age:1");
        monitor.update(mq);
        Matches<?> matches = monitor.match(doc, SimpleMatcher.FACTORY);
        MatchesAssert.assertThat(matches)
        .matchesDoc("doc1")
        .hasMatchCount("doc1", 1);
    }
```

> Running uk.co.flax.luwak.TestMonitor
Tests run: 12, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.452 sec <<< FAILURE!
matchIntPointfields(uk.co.flax.luwak.TestMonitor)  Time elapsed: 0.023 sec  <<< FAILURE!
java.lang.AssertionError:
Expecting actual not to be empty
        at uk.co.flax.luwak.assertions.MatchesAssert.matchesDoc(MatchesAssert.java:42)
        at uk.co.flax.luwak.TestMonitor.matchIntPointfields(TestMonitor.java:101)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

my pr is here that has my test. https://github.com/flaxsearch/luwak/pull/148

**Comment by romseygeek** [comment]
The default lucene query parser doesn't understand Point fields, which is why this doesn't work.  I have an open JIRA ticket for that (https://issues.apache.org/jira/browse/LUCENE-7804) but haven't had the bandwidth to work on it properly recently - feel free to take a look and use it!

**Comment by shawnfeldman** [comment]
thanks for getting back to me will take a look at the patch

**Comment by shawnfeldman** [comment]
FieldValueQuery seems to be missing in the lucene master

**Comment by shawnfeldman** [comment]
Looks like it became new TermQuery

**Comment by shawnfeldman** [comment]
was able to get pointfields working by adding my own query parser, if its worth it i can submit a pr back at some point.  

here's https://github.com/flaxsearch/luwak/pull/148/files#diff-da1d2bd1b3828925ab9b0f3418ed2594

**Comment by shawnfeldman** [comment]
would you be willing to accept a pr if i add an alternate query parser?  Can add alot more tests to prove it works for both cases text and point fields?

**Comment by shawnfeldman** [comment]
heres my pr https://github.com/flaxsearch/luwak/pull/148
