### ISSUE TITLE
Quick Question: Is there a way to share monitor using index on FSDirectory to be shared by different threads, 

### ISSUE THREAD

**Issue by ashabbir** [flaxsearch/luwak#174]
i have search engine implementation in Scala running with 40 000 saved queries and a few tera bytes of free text documents.
I create  a monitor using FSDirectory. Now to speed up my searches i would like to multi thread the search part.
I understand the monitor uses an Index Writer for Query Index. I am running into lock issues with multiple threads and i cant bring in a thread safe index Reader inside a monitor. 
Are their any plan to bring in multi threaded support for monitor object.
Is there a solution already that i am missing.

**Comment by mjustice3** [comment]
Not sure if this is what you want but there is a ParallelMatcher with a configurable 'threads' parameter that can execute the search phase of monitoring in parallel. E.g. set up a ParallelMatcherFactory<QueryMatch> with 8 threads and then pass it as the 2nd parameter to Monitor.match(DocumentBatch docs, MatcherFactory<T> factory). In your case if the 40K queries are filtered down to 4K by the presearcher for a particular document, then those 4K remaining queries would be run in parallel across the 8 ParallelMatcher threads. This works well in our setup.

**Comment by romseygeek** [comment]
You should only have a single Monitor object, but you can index and query it from multiple threads, or use the ParallelMatcher as Martin describes.

**Comment by ashabbir** [comment]
I was thinking about distributing my incoming stream on a spark cluster

Have different nodes in my cluster read of the same index

Right now I think I m gona using GlusterFs to replicate the index and then use that per node

Process:
Every morning I refresh the query index (that takes about 40 mins and I get an index on disk which is around 9 GB
Copy it over to different machines, each worker in my cluster gets 1 copy of index



Latter I will look into introducing an IndexReader in Luwak after my current project is done. 

regards
Ahmed

**Comment by romseygeek** [comment]
Different nodes will indeed require their own copies of the Monitor.

I'll close this for now, feel free to re-open if you run into more problems.
