### ISSUE TITLE
SpanFirstQuery with Luwak

### ISSUE THREAD

**Issue by amazoyer** [flaxsearch/luwak#178]
Hi,

I tried to use SpanFirstQuery on Luwak with no success. Is this kind of query supposed to work out-of-the-box with Luwak, or should I implement a specific TermFilteredPresearcher?

Here is the piece of code that I tried to test this feature on version 1.5 of Luwak:

        // query + data
        String fieldValue = "term1 term2";
        String fieldName = "field";
        Query query = new SpanFirstQuery(new SpanTermQuery(new Term(fieldName, "term2")), 1);
        String docId = "doc1";

        // lucene index
        RAMDirectory directory = new RAMDirectory();
        IndexWriter writer = new IndexWriter(directory,  new IndexWriterConfig(new StandardAnalyzer()));
        Document document = new Document ();
        document.add(new TextField(fieldName, fieldValue, Field.Store.YES));
        writer.addDocument(document);
        writer.close();
        IndexReader reader = DirectoryReader.open(directory);
        IndexSearcher searcher = new IndexSearcher (reader);
        TopDocs results = searcher.search(query, 1);
        System.out.println("Lucene hits : " + results.totalHits);

        // luwak index
        Monitor monitor = new Monitor(new LuceneQueryParser(fieldName), new TermFilteredPresearcher());
        MonitorQuery mq = new MonitorQuery("query1", query.toString());
        monitor.update(mq);
        InputDocument doc = InputDocument.builder(docId).addField(fieldName, fieldValue, new StandardAnalyzer()).build();
        System.out.println("Luwak hits : " + monitor.match(DocumentBatch.of(doc), SimpleMatcher.FACTORY).getMatchCount(docId));
``

I got the following output : 
Lucene hits : 0
Luwak hits : 1
Luwak reports a match but it shouldn't.

Thank you for your help,

Regards,

Aurelien

**Comment by mjustice3** [comment]
Your problem is feeding  SpanFirstQuery.toString() into a LuceneQueryParser and expecting to get a SpanFirstQuery back out. It doesn't work that way. Add this to your test:

```
        Query query = new SpanFirstQuery(new SpanTermQuery(new Term(fieldName, "term2")), 1);
        LuceneQueryParser parser = new LuceneQueryParser(fieldName);
        Query query2 = parser.parse(query.toString(), null);
```

and you'll see that query2 is not at all the same as the original query.

**Comment by amazoyer** [comment]
Thank you for your answer. So I guess the best option in my case would be to instantiate a MonitorQuery directly from a Lucene Query object, avoiding this unneeded serialize/deserialize phase? Is this possible with Luwak?

Thank you

**Comment by mjustice3** [comment]
This is speculation on my part since I'm not the designer, but I think the idea is that Luwak will be embedded inside a service that receives queries from an external source. Hence there must be a string form of some sort. It is fairly easy to build a Monitor with a custom query parser. This is what we do although we don't support SpanFirstQuery. Is there an existing parser out there that knows about SpanFirstQuery? If so, then you should be able to plug it into Luwak.

**Comment by amazoyer** [comment]
Finally, I used the ExtendableQueryParser to achieve this and it worked. Thank you for your advice.
