### ISSUE TITLE
Queries statistics

### ISSUE THREAD

**Issue by prog8** [flaxsearch/luwak#19]
I think logging queries statistics can be very helpful. Sometimes there are queries that regularly pass presearcher phase and never match on MemoryIndex phase. And another situation there can be many queries that match MI always (if presearcher it pass presearcher phase).

I think collecting such metrics can help to understand specification of queries and can lead in future to reduction of a number of queries that have to be checked in MI.

**Comment by romseygeek** [comment]
I've just pushed db5da4474a1a7f24db79a7e372152e1c3bb9db4d, meaning that you now get a list of queries selected by the presearcher in your Matches object.  You can combine this with the actual set of matches to calculate misses.
