### ISSUE TITLE
Index a range query using NumericRangePrefixTree

### ISSUE THREAD

**Issue by dsmiley** [flaxsearch/luwak#22]
I just watched your presentation on Luwak and heard of your difficulty in inverting a range query into an indexed document.  I have the answer :-)

https://issues.apache.org/jira/browse/LUCENE-5648

Ok so technically this issue is just for dates but at it's core it's more abstract and could be modified to numbers generically.  In fact as a total hack that I'm pretty sure will work, with no effort, just convert your number into a Date and and pass it in.  It supports the entire range of a long, which is tested.

**Comment by romseygeek** [comment]
I'm going to close this for now, with a view to using lucene 6 points to do this instead at some point.  Thanks for the suggestion, though!
