### ISSUE TITLE
Which to create pull requests against?

### ISSUE THREAD

**Issue by dcollins53** [flaxsearch/luwak#50]
@romseygeek just wanted to check what your current "trunk" branch was for creating any pull requests.  There is 1.1.x and topic/aw-parallel (which we use internally), but seems to have necessary changes, but I wasn't sure which was most current?

We have some suggested fixes such as improved index stats in the monitor and a queryIds() API for monitor, but just wanted to check what to generate the PRs against.

**Comment by romseygeek** [comment]
Hi Daniel, in this repository the best branch to generate pull requests against is 1.1.x, I think.  I need to clean up the branches here a bit though!

**Comment by romseygeek** [comment]
I've brought ```master``` up to date with all the changes in ```1.1.x```, so I think that's the best branch to issue pull requests against now.  I may even get round to doing an actual release.

**Comment by dcollins53** [comment]
Cheers, will try to isolate small/isolated changes to start with to get us moving onto common ground.
