### ISSUE TITLE
TermQuery on a numeric field fails to match for some values

### ISSUE THREAD

**Issue by dcollins53** [flaxsearch/luwak#51]
We have some numeric fields in our "schema", which result in a TermQuery using a packed int form as the bytesref. e.g. something like language_id:9 but the 9 is encoded as a packed int in the bytesref.

These queries never generate any matches.

On investigation, TermFilteredPresearch::collectTerms gets confused by this, since it generates a space-separated list of term data (but that QueryTerm is a string format of a bytesref, so could be something like {60, 8, 0, 0, 0, 9} which is the packed form of the integer 9, but 9 is also the tab character!  Luwak's monitor uses an IndexWriter with a WhitespaceAnalyzer, which removes the spaces, but also removes some characters from the QueryTerm, which means we store an incorrect bytesref in the Presearcher index.

Trying to come up with a test case for this, but it may be due to our parser, I'm not sure how to get a packed int byterefs out of LuceneQueryParser.

Any thoughts (other than switching to strings :) )?

A numeric range would work, since RangeQuery ignores the presearcher currently.

**Comment by romseygeek** [comment]
Hm, this sounds like it's a bug in the QueryAnalyzer actually, QueryTerm should probably just be using Term (or BytesRef) rather than trying to coerce things to Strings.

I'm a bit snowed under at the moment, but I'll try to look at this properly soon

**Comment by dcollins53** [comment]
Ok, still trying to find a decent way to "show" this properly just within Luwak, it seems to be a product of the QueryParser that we use (or the analysis chain which our query parser uses).

For the meantime, we'll make use of a string field instead, but will try to work on this in background too,.

**Comment by romseygeek** [comment]
If it's for testing, could you just create an anonymous MonitorQueryParser subclass that returns a TermQuery with the appropriate bytes set?

**Comment by romseygeek** [comment]
Just out of interest, how are you adding numeric fields to an InputDocument?  MemoryIndex currently requires a TokenStream, which IntField and friends don't support.  Would be a useful thing to add arbitrary Fields to MemoryIndex, but that's something of a bigger change...

**Comment by romseygeek** [comment]
OK, I've knocked something up: see #52

**Comment by dcollins53** [comment]
We use a Solr schema, and a Solr analysis chain (we give it our schema.xml and it creates the necessary analysis), so in our wrapper to Luwak we just pass through our Analyzer, which must be generating the BytesRef, since Solr knows about TrieField, and can generate numeric output (I think).

**Comment by dcollins53** [comment]
Managed to knock up a more complex test case.

```java
    @Test
    public void filtersOnNumericTermQueries() throws IOException {

        // Rudimentary query parser which returns numeric encoded BytesRefs
        Monitor numeric_monitor = new Monitor(new MonitorQueryParser() {
            @Override
            public Query parse(String queryString, Map<String, String> metadata) throws Exception
            {
                BytesRef br = new BytesRef();
                NumericUtils.intToPrefixCoded(Integer.parseInt(queryString), 0, br);

                Term t = new Term(TEXTFIELD, br);
                return new TermQuery(t);
            }
        }, presearcher);

        MonitorQuery query1
                = new MonitorQuery("query1", "8");
        MonitorQuery query2
                = new MonitorQuery("query2", "9");
        MonitorQuery query3
                = new MonitorQuery("query3", "10");
        MonitorQuery query4
                = new MonitorQuery("query4", "11");
        MonitorQuery query5
                = new MonitorQuery("query5", "12");
        MonitorQuery query6
                = new MonitorQuery("query6", "13");
        MonitorQuery query7
                = new MonitorQuery("query7", "14");
        MonitorQuery query8
                = new MonitorQuery("query8", "15");
        numeric_monitor.update(query1, query2, query3, query4, query5, query6, query7, query8);

        NumericTokenStream nts = new NumericTokenStream(1);
        nts.setIntValue(Integer.parseInt("8"));

        InputDocument doc = InputDocument.builder("doc1")
                .addField(TEXTFIELD, nts)
                .build();

        Matches<QueryMatch> matcher = numeric_monitor.match(doc, SimpleMatcher.FACTORY);
        assertThat(matcher)
                .matches("doc1")
                .hasMatchCount(1)
                .matchesQuery("query1")
                .hasQueriesRunCount(1);

        nts.setIntValue(Integer.parseInt("9"));

        doc = InputDocument.builder("doc1")
                .addField(TEXTFIELD, nts)
                .build();

        matcher = numeric_monitor.match(doc, SimpleMatcher.FACTORY);
        assertThat(matcher)
                .matches("doc1")
                .hasMatchCount(1)
                .matchesQuery("query2")
                .hasQueriesRunCount(1);

        numeric_monitor.close();
    }
```

If I add this test to `TestMatchAllPresearcher`, then its all good, but it (currently) fails in `TestTermPresearcher`, will try with your fix tomorrow.  I think the NumericUtils stuff is from 4.8.1, that is probably in BytesRefBuilder in trunk, but I'm still on an older codebase.

This test shows up the issue since the value 9 == TAB, which was being removed by the WhitespaceAnalyzer, the document with value of 8 always worked, but 9-13 fail, and then 14 works again...

Will try to format this as a proper PR (against trunk) tomorrow.

**Comment by romseygeek** [comment]
Fixed by 6650f74fd95f1fb12c69dcfa17e50879d660731a

**Comment by dsmiley** [comment]
@romseygeek earlier you said MemoryIndex requires a TokenStream and that IntField doesn't provide one.  You should check out NumericTokenStream.

**Comment by andyetitmoves** [comment]
The test case above actually uses one..
