### ISSUE TITLE
DisjunctionMaxQuery no longer supported in the new SpanRewriter

### ISSUE THREAD

**Issue by dyshi** [flaxsearch/luwak#61]
@dcollins53  @romseygeek in commit b69d0293d6ea81deb551813248f59e9b13b3acbb, the new SpanRewriter no longer supports DisjunctionMaxQuery. Should I add it back?

Thanks!

**Comment by romseygeek** [comment]
Oops, yes, that's an oversight.  You just need to add a clause to SpanRewriter I think?

**Comment by dyshi** [comment]
Also could I clarify my understanding. From looking at how the boolean query is rewritten, since disjunction max is just a boolean query with all ORs and a different scoring mechanism, the implementation of ForceNoBulkScoringQuery should suffice to wrap the disjunction max query as well right?

**Comment by romseygeek** [comment]
ForceNoBulkScoringQuery works for all queries - all it does is ensure that docs are scored one-by-one, which we need if we're extracting spans from them.  It's mainly there to stop BooleanWeight doing bulk scores.

**Comment by dyshi** [comment]
Ok then I'll just wrap the DisjunctionMaxQuery in that and put the change in a new branch

**Comment by romseygeek** [comment]
It shouldn't actually be necessary to wrap it, as DisjunctionMaxWeight doesn't have a specialized bulk scorer.

**Comment by dyshi** [comment]
I've submitted a first draft, let me know any changes, thanks!
https://github.com/flaxsearch/luwak/pull/62
