### ISSUE TITLE
Luwak Scoring

### ISSUE THREAD

**Issue by dyshi** [flaxsearch/luwak#64]
@romseygeek  Currently Luwak scoring creates a scorer for each query that is stored. Since we have a lot of queries and only 1 document during the matching stage, how come we don't create 1 scorer and uses that same one across all the queries? 
Thanks!

**Comment by romseygeek** [comment]
Not sure I follow - Scorer objects are created by queries, it doesn't make any sense to think of them as re-usable between queries?

**Comment by dcollins53** [comment]
I think the idea is that we are trying to make use of IDFs from a Solr index in our Luwak scoring.  So if we are using conventional TF/IDF scoring, logically we want to cache the IDF data between queries, though the TF part will have to be re-calculated in each query.

**Comment by romseygeek** [comment]
You should be able to do that in a custom Similarity - extend TFIDFSimilarity and override idfExplain().

**Comment by dyshi** [comment]
but each time indexSearcher's search method is called a new weight and then a new SimScorer is created. I guess we can't really make it so that only 1 SimScorer is used across different queries without rebuilding part of lucene. I'm probably prematurely trying to optimize our scoring
