### ISSUE TITLE
Flip the order of clauses in FieldFilterPresearcherComponent.adjustPresearcherQuery()

### ISSUE THREAD

**Issue by mjustice3** [flaxsearch/luwak#65]
The component builds a new BooleanQuery like this:

        bq.add(presearcherQuery, BooleanClause.Occur.MUST);
        bq.add(filterClause, BooleanClause.Occur.MUST);

In our use case, and I suspect many others, the filterClause is significantly simpler than the presearcherQuery. Just wondering if it would make sense to flip the order of add's?

        bq.add(filterClause, BooleanClause.Occur.MUST);
        bq.add(presearcherQuery, BooleanClause.Occur.MUST);

Seems to speeds up our application substantially. Or maybe there could be a parameter that allows choice of order?

**Comment by romseygeek** [comment]
Which version of lucene is this with?  5.3 should choose which clause to advance first using the cost() API, so the order in which they're added won't make a difference.

**Comment by mjustice3** [comment]
Ahh, ok. We're still on 4.8 but will be moving to 5.3 eventually.

**Comment by dcollins53** [comment]
Yet another reason for us to get keep up with trunk!
