### ISSUE TITLE
Monitor class and high concurrency

### ISSUE THREAD

**Issue by lookfwd** [flaxsearch/luwak#68]
Hello. We are running a few high-concurrency, high write/update scenarios around uk.co.flax.luwak.Monitor class and we've seen the huge improvements around concurrency in latest revision. Thank you very much!

I think we might have identified a few interesting corner cases (I might as well be wrong - those issues are very hard to reproduce and reason).

### Case 1.

One example is [during update](https://github.com/flaxsearch/luwak/blob/master/luwak/src/main/java/uk/co/flax/luwak/Monitor.java#L388)

    Thread 1 starts an update...
    public List<QueryError> update(Iterable<MonitorQuery> queries) {
    ...
            for (MonitorQuery query : queries) {
                try {
                    writer.deleteDocuments(new Term(FIELDS.del, query.getId()));

    // ---> We are here, deleting "A" ... we will later update it to "B" by adding addDocument()
    // during commit(). Thread pauses.
    // Thread 2 does does an irrelevant delete or update. As part of its commit...

    private synchronized void commit(List<Indexable> updates) throws IOException {
    ...
            writer.commit();
            manager.maybeRefresh();
    ...
    // it calls writer.commit(); Which commits our delete from Thread 1.
    // 
    // At this point any match operation won't see the document we accidentally deleted unless
    // the original thread resumes and completes the operation.

The easiest way I can see is moving `writer.deleteDocuments(new Term(FIELDS.del, update.id));` inside `commit()`. Still there's a race condition but should be way shorter as far as I can see. This issue will be very hard to fix as long as we use a single `writer`.

### Case 2.

Also in [line 497](https://github.com/flaxsearch/luwak/blob/master/luwak/src/main/java/uk/co/flax/luwak/Monitor.java#L497)

    // Thread 1 grabs a snapshot for a match here:
    searcher = manager.acquire();
    // Thread 1 pauses.
    // An update (ill case above) or delete happens from another thread and `purgeCache()`,
    // gets called erasing a few hashes from the cache.
    // Thread 1 resumes and a bit later it does...
    collector.setQueryMap(this.queries);
    // This gets the new cache which will be missing hashes.

A solution here should be to wrap this critical section on a `purgeLock.readLock()`.

### Case 3.

In general in order to isolate impact of potential present or future race conditions I think it would be great to check for null on those two cases where we use  references to `queries`; one in [line 328](https://github.com/flaxsearch/luwak/blob/master/luwak/src/main/java/uk/co/flax/luwak/Monitor.java#L328) and one in [line 620](https://github.com/flaxsearch/luwak/blob/master/luwak/src/main/java/uk/co/flax/luwak/Monitor.java#L620).  Now we throw an exception that fails the entire operation (`purgecache()` or `match()`). 

Additionally making `queries` variable `volatile`, exactly as `purgeCache` should help avoiding potential visibility problems among threads.

Obviously this isn't bug report or a pull request. I'm just opening a discussion to see if I'm missing something obvious and potentially coordinate on improving this further.

Cheers,
Dimitris

**Comment by romseygeek** [comment]
Hi Dimitris,

Thanks for the reports - I'm glad to hear that you're using luwak and that you're seeing improvements!

I think you've identified genuine issues in each case here, and your suggested solutions seem correct - in case 1 moving deletions directly into commit() will I think remove the race entirely, as that whole method is synchronized?  Do you want to open pull requests with your fixes?

**Comment by lookfwd** [comment]
Hello,
> in case 1 moving deletions directly into commit() will I think remove the race entirely
As far as I can see yes - that's great!
Excellent, I will try to prepare pull request tomorrow.

**Comment by romseygeek** [comment]
Hi Dimitris,

I ended up implementing these myself, as I want to get a 1.3.0 release out :-)  See:
Case 1: 18fc64402b8865ba4a743210bc23c07e891ca1c1
Case 2: 16cf9e764fe35fd1793bf87fe7be3a0a8c914f59
Case 3: feeae72e3576f394b9b9e3b8d922ced73a06e563

Thanks for raising the issue, and for your suggested fixes!

**Comment by lookfwd** [comment]
Awesome, great - will send you an e-mail.
