### ISSUE TITLE
Unable to reconize DocumentBatch.java in the artifacts 

### ISSUE THREAD

**Issue by ronagrawal** [flaxsearch/luwak#69]
Thanks for this library. 
The following artifacts is unable to recognize DocumentBatch class in the root folder
<dependency>
	<groupId>com.github.flaxsearch</groupId>
	<artifactId>luwak</artifactId>
	<version>1.2.0</version>
</dependency>

**Comment by romseygeek** [comment]
Hi,

DocumentBatch is only in master, not in any released version (in fact I only pushed it to master today!).  I plan on doing a 1.3.0 release in the next few weeks, though.

**Comment by ronagrawal** [comment]
Hi

I should I have verified by cross checking the revision history.
Thank you for this library.

Ronak
