### ISSUE TITLE
Request: Get Set of documents that match a query

### ISSUE THREAD

**Issue by ronagrawal** [flaxsearch/luwak#72]
How can we get the set of all documents id that match particular query id ?

**Comment by romseygeek** [comment]
In a particular batch?  There isn't a particular method to do that at the moment, you could do something like:

{code}
Set<String> matchingDocs = new HashSet<>();
for (DocumentMatches dm : matches) {
    for (QueryMatch m : dm) {
        if (m.getQueryId().equals(expectedId))
            matchingDocs.add(m.getDocId());
    }
}
{code}

This would be a useful method to add to Matches<> - do you want to open a pull request?

**Comment by ronagrawal** [comment]
I am doing sort of similar thing now.However, making a pull request for this would be a good idea for other devs.

Another Topic: Can We send a json object and search data in a particular field ?

**Comment by romseygeek** [comment]
Luwak doesn't concern itself with external representations, you'd need to write some Java code to translate the json into an InputDocument with the appropriate fields.
