### ISSUE TITLE
Wildcard issue with ComplexPhraseQueryParser

### ISSUE THREAD

**Issue by PetaPetaPeta** [flaxsearch/luwak#73]
I am using an altered version of the ComplexPhraseQueryParser(https://lucene.apache.org/core/4_1_0/queryparser/org/apache/lucene/queryparser/complexPhrase/ComplexPhraseQueryParser.html).

Here's a couple of example queries that show how it should act and how it actually acts. Note that all these queries work as expected when I use the queryparser directly with Solr. 

`title:foo AND NOT title:"foo bar"`

Title | Expected | Actual
------|-------------|---------
foo | Match | Match
foo bar | No match | No match
foo barbaz | Match | Match

`title:foo AND NOT title:"foo ba*"`

Title | Expected | Actual
------|---------|---------------
foo | Match | No match
foo bar | No match | No match
foo fighters | Match | No match

`title:"foo ba*"`

Title | Expected | Actual
------|---------|---------------
foo | No match | Match
foo bar | Match | Match
foo fighter | No match | Match
foo fighters | No match | No match
foo fighterss | No match | Match

As you can see it starts acting very sporadically when I use wildcards. I assume that it is because the query is not stored correctly in the monitor. I am using the modified ComplexPhraseQueryParser when initiating the monitor as follows:
```java
this.monitor = new Monitor(new ModifiedComplexPhraseQueryParser(FIELD, ANALYZER), new TermFilteredPresearcher());
```

How do I go about debugging this? What could be wrong?

**Comment by romseygeek** [comment]
Hi Peter,

There are a couple of things you can do to see where the bug is:
* run it through the Monitor with a MatchAllPresearcher.  This should tell you if the bug is in how the query is being indexed, or if it's a problem with how things are being matched once they've been selected.
* If the problem is in the presearcher, you can use TermFilteredPresearcher.showQueryTree(Query q) to get an idea of exactly how the query is being indexed.  It may be that the parser you're using is generating queries that luwak doesn't know how to deal with, although the fallback case ought to be that it just always gets selected.

**Comment by romseygeek** [comment]
I've had a quick look with the *unaltered* ComplexPhraseQueryParser, and it seems to work as expected:
```
@Test
    public void testComplexPhraseQueryParser() throws Exception {
        MonitorQueryParser parser = new MonitorQueryParser() {
            @Override
            public Query parse(String queryString, Map<String, String> metadata) throws Exception {
                return new ComplexPhraseQueryParser("title", ANALYZER).parse(queryString);
            }
        };

        try (Monitor monitor = new Monitor(parser, new TermFilteredPresearcher())) {
            monitor.update(new MonitorQuery("1", "title:foo AND NOT title:\"foo ba*\""));
            InputDocument doc = InputDocument.builder("doc").addField("title", "foo", ANALYZER).build();
            assertThat(monitor.match(doc, SimpleMatcher.FACTORY))
                    .matchesDoc("doc");
        }

    }
```

So it might be something to do with the queries that are actually being generated by your modified version?

**Comment by PetaPetaPeta** [comment]
Thanks for looking into this so quickly and I'm sorry for being slow with my response!

It seems like the issue lies in how I initialize the monitor. The following does not work:
````java
    @Test
    public void testInitPositional() throws Exception {
        try (Monitor monitor2 = new Monitor(new ModifiedComplexPhraseQueryParser("title", ANALYZER), new TermFilteredPresearcher())) {
            monitor2.update(new MonitorQuery("1", "title:foo fight*"));
            InputDocument doc = InputDocument.builder("doc").addField("title", "foo", ANALYZER).build();
            assertThat(monitor2.match(doc, SimpleMatcher.FACTORY)).hasMatchCount(0);
        }

    }
````
The test above fails, but if I alter the code to initialize the monitor like in your example it works. Do you know what the reason is for this?

**Comment by romseygeek** [comment]
Can you share your modified parser code?  It may be something to do with how that's being initialized.

Also, this query: ```title:foo fight*``` will be parsed into 'title:foo' OR 'title:fight*' - could need to add quotes around the query terms (at least, if it works the same way as the standard parser).

**Comment by PetaPetaPeta** [comment]
I am unfortunately not able to share all of the parser code as it is propriatary. I have however shared the initialization code here: http://pastebin.com/JEWKdXy3

And you are right - the example above wasn't correct. I have just spent some time doing some more tests and they seem to fail.

title:\"cell bio*\"
Title | Expected | Actual
------|-------------|---------
"cell" | no match | no match
"cell bio" | match | no match
"cell biology" | match | no match
"cell tech" | no match | no match

It does seem to suggest that there is an issue with the queries that are being generated. I think I might have an old version of Luwak as I don't have access to TermFilteredPresearcher.showQueryTree - is it a new function?

**Comment by romseygeek** [comment]
Which version of luwak are you using?  It should be in 1.2 and 1.3.

**Comment by PetaPetaPeta** [comment]
I am in 1.1 so I will just try and update it.

**Comment by PetaPetaPeta** [comment]
Okay I am updated now. I hit a few hitches, but nothing too bad.

I have gotten the function showQueryTree to work, but I get the following result:
````
AnyNode [ANY :Can't extract terms from solr.ComplexPhraseQueryParser$ComplexPhraseQuery] 0.0
````

**Comment by romseygeek** [comment]
OK, so the query analyzer doesn't know what to do with that query and will just add it to its index under an ANY token, which will mean that it will always be selected by the presearcher.  So you won't be getting any of the nice presearcher speedups.

However, that won't be the cause of the errors you're seeing above, because the query will be selected, it just isn't matching.

Do the failing "cell biology" tests work if you use the pattern I described above, where a new parser is created for each query parsed?  It may be that your query parser isn't resetting its state properly between each parse() call.

**Comment by PetaPetaPeta** [comment]
So the test I have set up looks like this: 

````java
@Test
public void testPositional() throws Exception {
    final TermFilteredPresearcher presearcher = new TermFilteredPresearcher();
    MonitorQueryParser parser = new MonitorQueryParser() {
        @Override
        public Query parse(String queryString, Map<String, String> metadata) throws Exception {
            Query q =  new ModifiedComplexPhraseQueryParser("title", ANALYZER).parse(queryString, null);
            presearcher.showQueryTree(q, System.out);
            return q;
        }
    };

    try (Monitor monitor = new Monitor(parser, presearcher)) {
        monitor.update(new MonitorQuery("1", "title:\"cell bio*\""));
        InputDocument doc = InputDocument.builder("doc").addField("title", "cell biology", ANALYZER).build();
        assertThat(monitor.match(doc, SimpleMatcher.FACTORY))
                .hasMatchCount("doc", 1);
    }
}
````
So it happens because the query isn't stored correctly in the index? Is there any way to check what is stored in the index?

**Comment by romseygeek** [comment]
OK, if I change that to use the plain ComplexPhraseQueryParser, the test passes.  Which suggests that it's actually something to do with the modifications you have in there.  Nothing to do with how the query is stored or isn't stored, it's just not being parsed into the lucene query that you think it should be.

**Comment by PetaPetaPeta** [comment]
You were right! It seems like ModifiedComplexPhraseQueryParser was interfaced a version of the ComplexPhraseQueryParser that was also altered. Changing this interface to point at the original from Lucene seems to make it work!

So it must be something with the difference between the two versions of the ComplexPhraseQueryParsers. I think I have enough to go on now to finish this and make it work fully! Thank you so much for your help and quick responses! :)

**Comment by PetaPetaPeta** [comment]
Okay, I am reopening this because the issue apparantly wasn't entirely solved.
````java
    static final String TEXTFIELD = "title";
    static final Analyzer ANALYZER = new StandardAnalyzer();
    private Monitor monitor;
    @Before
    public void setUp() throws IOException {
        final TermFilteredPresearcher presearcher = new TermFilteredPresearcher();
        MonitorQueryParser parser = new MonitorQueryParser() {
            @Override
            public Query parse(String queryString, Map<String, String> metadata) throws Exception {
                Query q =  new ComplexPhraseQueryParser(TEXTFIELD, ANALYZER).parse(queryString);
                return q;
            }
        };

        monitor = new Monitor(parser, presearcher);
    }

    @Test
    public void wildcard() throws Exception {
        String query = "title:\"biolo*\"";
        String matching_document = "cell biology";
        String non_matching_document = "cells";

        monitor.update(new MonitorQuery("query1", query));

        DocumentBatch batch = DocumentBatch.of(
            InputDocument.builder("doc1").addField(TEXTFIELD, matching_document, ANALYZER).build(),
            InputDocument.builder("doc2").addField(TEXTFIELD, non_matching_document, ANALYZER).build()
        );

        assertThat(monitor.match(batch, SimpleMatcher.FACTORY))
                .hasMatchCount("doc1", 1)
                .matchesDoc("doc1")
                .matchesQuery("query1", "doc1");
    }
````
This test seems to fails as it does not have any matches. However if I change it to use the query 'title:"test biology"' it works. I am using the ComplexPhraseQueryParser included with Solr 5.3.0.

Can you verify that you also experience this behaviour?

**Comment by romseygeek** [comment]
Hi Peter,

You're getting an error thrown by the ComplexPhraseQueryParser, I don't think it allows you to include wildcards in phrases?  If you examine the Matches object you get back from ```monitor.match()```, you'll see it has a getErrors() method which you need to check.

**Comment by PetaPetaPeta** [comment]
Hello Alan!

Thanks again for the quick response. It's weird that the error is thrown because it works with "cell bio*". So as long as there's a space in there it seems to work. I was thinking that this was a bug with ComplexPhraseQueryParser, but it seems to work when I run it through Solr.
Is there any way to get a more elaborate error message than what is given here?

**Comment by PetaPetaPeta** [comment]
I found it! The comment here in a JIRA issue seems to explain it:
https://issues.apache.org/jira/browse/SOLR-1604?focusedCommentId=13471505&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-13471505
"This parser expects at least two clauses inside quotes."

That seems to be the issue here. Now I just need to fix it and I should be good to go :+1: Thanks again for helping!
