### ISSUE TITLE
Use of SpanScorer?

### ISSUE THREAD

**Issue by dcollins53** [flaxsearch/luwak#76]
org.apache.lucene.search.spans.SpanExtractor (in Luwak trunk) makes use of SpanScorer, which is present in Lucene 5.3 (the pre-requisite for Luwak).

However, LUCENE-6845 then removed this class in 5.4, and LUCENE-6919 brought it back(!) in branch_5x.

Tried building Luwak with 5.4 and it won't compile, so do we need to do something about use of SpanScorer, or do we need to port LUCENE-6919 back to 5.4?

**Comment by romseygeek** [comment]
I have another project that needs to run luwak on 5.4, and am working on a port at the moment.  I'm sort of unsure how to deal with this in terms of releases, as there won't actually be any new functionality, just a change of lucene version - maybe I should do a 1.3.0-lucene5.4 release line?

**Comment by dcollins53** [comment]
Meh, I hate it when APIs like this change, confused me more as it came back in 5.x, is SpanScorer coming back for good or going away?

Its certainly not a patch, so 1.3.1 is wrong!
If you release 1.4, then the 1.3 "release" only work on Lucene 5.3, (and nothing later) which isn't great.
I'm inclined not to specifically call it 1.3.0-lucene5.4, since presumably it will work in 5.5 (and 6.0) when they come out, so that could be misleading.

Lesser of two evils, I'd probably call it 1.4, and just flag up the 1.3 release branch as only for Lucene 5.3.  I don't really like it, but I like the alternatives less!

P.S. do you get test failures with 5.4 in testBoostsArePreserved(uk.co.flax.luwak.TestQueryDecomposer): (..)??  Trying out our internal branch and that has some cherry-picks from 5.5, so not sure if I've pulled the wrong thing back or something has changed in the query structure..

**Comment by dsmiley** [comment]
I think 1.4 makes the most sense.  It needn't have new features.  I've had to grapple with the same challenge in my https://github.com/OpenSextant/SolrTextTagger and I've just accepted this is how it is, and when I can I push back on changes in Lucene that are needlessly backwards incompatible (e.g. that SpanScorer/Weight stuff :-).  Lucene 6 is the ideal version to make incompatible changes.

**Comment by romseygeek** [comment]
I guess I can't complain too much about the changes to the Spans API, seeing as I was the one who made them :-/  Ideally I want to push some of this stuff back into core lucene anyway, but I don't think it's quite there yet.

I'll move to 5.4 and do a 1.4 release then.  Thanks for your input, gents.

**Comment by romseygeek** [comment]
I've pushed a new branch, topic/lucene-5.4.  The main changes are some extra code to handle the new BoostQuery, mainly around span rewriting and query decomposition.  The tests are a bit skimpy here, so please do test this out against your query corpus and open issues for any bugs you find!

**Comment by dcollins53** [comment]
@romseygeek, your changes are on master now, so are we done with this? Going to close this off, re-open if you object :)
