### ISSUE TITLE
how can we get back the actual query as well as the queryid for HighlightsMatch?

### ISSUE THREAD

**Issue by holajoyce** [flaxsearch/luwak#77]
how can we get back the actual query as well as the queryid for HighlightsMatch?

Thanks

**Comment by romseygeek** [comment]
You can get the MonitorQuery just by calling Monitor.getQuery().  To retrieve the lucene Query object itself you'll have to write your own CandidateMatcher that extends HighlightingMatcher and override doMatchQuery().

It would be nice to be able to compose matchers, but that's not really possible with the way things are structured at the moment, unfortunately.
