### ISSUE TITLE
Presearcher randomness?

### ISSUE THREAD

**Issue by mjustice3** [flaxsearch/luwak#78]
More of a question than an issue. I'm in the process of upgrading my app from Luwak master 46d5465 to 4bd3391.  After merging I ran my benchmarking tests to make sure the results were the same. They are, but then I also happened to look at the CandidateMatcher's queriesRun values, which are slightly different. I reran the benchmarks just to be sure, but then I noticed that the queriesRun changed from run to run within the same Luwak version. The differences are small, typically 1 or 2 queries out of ~400/doc. Just curious if that is something expected?

**Comment by romseygeek** [comment]
Hm, no, it should be entirely deterministic.  The Matches object reports which queries were selected by the Presearcher, so it should at least be possible to work out what the discrepancies are, though.

**Comment by mjustice3** [comment]
You mean the presearcherHits? If I temporarily change that from a Set to a List in order to account for query decomposition, then the size is the same as the queriesRun and I can dump them out and see the discrepancies from run to run.

A clue is that, if I load all the queries once and run the same doc against them, say 5 times, then the presearcherHits are always the same. But if I stop/restart so that the queries  are reloaded for each run, then the hits can vary from run to run. So it seems like it may have something to do with the way the queries are loaded. Was thinking possibly that, since there is discretion in building the presearcher index for conjunctions (as I understand it), there may be some non-determinism creeping in. E.g, for code such as 

                if (child.weight(this) > selected.weight(this))
                    selected = child;

the actual child selected can depend on iteration order if the weights are equal. But why would the iteration order ever change?

Oh well, you can close this issue if you like. As I mentioned  at the outset, the document matches are consistent across runs and that's ultimately what we care about.

**Comment by mjustice3** [comment]
Yeah, that's it. If I change QueryTree's children from a HashSet to a LinkedHashSet then I get deterministic presearcherHits. Closing as understood and not a problem.

**Comment by romseygeek** [comment]
Nice detective work, thanks!  Could you open a pull request for that change?  It's worth not having weird discrepancies like this appearing in logs, etc.
