### ISSUE TITLE
Block join question

### ISSUE THREAD

**Issue by jej2003** [flaxsearch/luwak#85]
With the addition of document batches would it be possible to slightly modify the document insertion code to add documents as a block so block join queries can be supported?

**Comment by romseygeek** [comment]
Hi, yes I think this would be pretty easy, just a change to MultiDocumentBatch.  Do you want to raise a pull request?

**Comment by jej2003** [comment]
I've not tried it as of yet as I'm not that familiar with how the block
insert would need to occur (I currently leverage solr for this). I will
take a look though and see what I can piece together.

**Comment by romseygeek** [comment]
Closing as discussion has moved to the pull request
