### ISSUE TITLE
Make Match objects Serializable

### ISSUE THREAD

**Issue by amilbourne** [flaxsearch/luwak#92]
I need so pass HighlightsMatch objects over the wire and hence need to Serialize them.  Would it be possible to make the Match classes Serializable?  Failing this, could the hits field be made protected so that a Serializable subclass could access it.

Perhaps this shouldn't be part of Luwak, but on the other hand the impact would be almost zero and it may be generally useful.

I haven't submitted a PR as I'm unsure of whether it would be desirable, but I'm happy to submit one if the reaction is positive.

This is really a very low priority request, but it would make my code more efficient :-).

**Comment by romseygeek** [comment]
I'm reluctant to make things Serializable as makes it difficult to change their internal structure in future.  Maybe the best solution here is just to make it easier to get at the internal hits Map with a getAllHits() method?

**Comment by amilbourne** [comment]
I understand your reservations about Serializable, although I personally treat any new version of a library as incompatible for serialization - because they often are and that's quite OK.

getAllHits() sounds like a reasonable compromise - do you want me to create a PR?

**Comment by romseygeek** [comment]
bq. do you want me to create a PR?

Yes please!

**Comment by amilbourne** [comment]
I do apologise for opening this issue and then going silent.  Things got a bit busy and I haven't had time to look at this again.  I'm not sure when I will get time to look at it.  Please feel free to close this issue if it is clutter - sorry.

**Comment by romseygeek** [comment]
No worries, I'll keep it open for a while - I may get round to it myself at some point :)
