### ISSUE TITLE
Creating a new field type

### ISSUE THREAD

**Issue by edvorg** [flaxsearch/luwak#93]
Hi. Sorry for creating an issue for that question, I just couldn't find a better place.
I need to create two new field types and make it to work with luwak percolator.
I need an ip field and date field that would work the same way they work in elasticsearch.
Does luwak support this kind of extension and if so, where should I look into?
Thanks.

**Comment by romseygeek** [comment]
Hi, don't worry about creating issues, that's what they're here for :)

Luwak works at the lucene level, and can take any FieldType and Query that you want to add to it, although the presearcher won't be helpful if it doesn't know anything about those fields or queries.  IP and date fields are both specialised numeric fields, so I'd look at the Trie*Field types.  Or if you're happy working on the bleeding edge, luwak master runs on lucene 6, which means you can use the new PointValues fields.

**Comment by edvorg** [comment]
Thank you for explanation. I wonder if I could use `LuceneQueryParser` with `PerFieldAnalyzerWrapper` that contains an analyzer for my new field type. I expect to get, say range queries on ip, working as well. That means I need a query parser to be able to parse these new fields as well. Do you think it would work?

**Comment by romseygeek** [comment]
You can try with just LuceneQueryParser, but I suspect you'll end up having to extend it somehow.

**Comment by edvorg** [comment]
Thank you!
