### ISSUE TITLE
No matches when using a custom analyzer

### ISSUE THREAD

**Issue by edvorg** [flaxsearch/luwak#94]
Hi. I'm making an elastic template analyzers parser to replace elastic percolation in my project with luwak. I have a document with a field:
```
name: software.LOG
```
My template for this field is:
```
                "name": {
                    "type": "string",
                    "search_analyzer": "generic_search",
                    "analyzer": "generic_index",
                },
```

Where search analyzers are:
```
                "generic_search": {
                    "tokenizer": "filename",
                    "filter": ["lowercase"]
                },
                "generic_index": {
                    "tokenizer": "filename",
                    "filter": ["lowercase"]
                },
```

Where tokenizer is:
```
                "filename": {
                    "pattern": "[^\\p{L}\\d]+",
                    "type": "pattern"
                },
```

And filter is `org.apache.lucene.analysis.core.LowerCaseFilter`

Parser eventually generates a custom analyzer with lowercase filter and pattern tokenizer for this field.

For search query I use a custom analyzer, that has `keyword tokenizer` and `lowercase filter`.

I'm trying it on the exact match query  `name:software.LOG`, but it doesn't give me any results.

Could it be a luwak issue?

Thanks.

**Comment by romseygeek** [comment]
Can you create a pull request with a failing test case illustrating the problem?  The other page to check out is https://github.com/flaxsearch/luwak/wiki/Debugging-Luwak

**Comment by edvorg** [comment]
Thanks. I'll make a pr tomorrow.

**Comment by romseygeek** [comment]
Hi, I had a quick look at this, and it's not a luwak problem, it's your tokenizer setup.  The field tokenizer is breaking "software.log" into two tokens, but the query tokenizer is keeping it as a single token, so they don't match.

**Comment by edvorg** [comment]
Checked with java regex.
```clojure
fuser> (def r (java.util.regex.Pattern/compile "[^\\p{L}\\d]+"))
#'fuser/r
fuser> (re-find r "Framework.log")
"."
```
You are right indeed.
I tried to use same analyzer for query, but got another problem.
On elastic  query `name:Framework.log` gives  me result with `{"name":"Framework.log"}`.
But with luwak I also get results like `{"name":"Software.log"}`.
I guess there is some difference in elastic and luwak queries.
Elastic makes sure, that every token from query is present in field.
Luwak find at least one matching token.
Is it possible to configure luwak to work the same way as elastic does?
Thanks.

**Comment by romseygeek** [comment]
Looks like the ES query parser uses AND as a default operator, while luwak's LuceneQueryParser just uses the default setting, which is OR.  You'll need to create your own MonitorQueryParser implementation that sets the default operator properly here.

**Comment by edvorg** [comment]
Thanks, found it here.
https://lucene.apache.org/core/3_0_3/api/core/org/apache/lucene/queryParser/QueryParser.html#setDefaultOperator(org.apache.lucene.queryParser.QueryParser.Operator)
